[project]
name = "gym-planning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AI DEV", email = "me@code.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
gym-planning = "gym_planning:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
